name: "seed-prod"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  PGDATABASE: ${{secrets.PGDATABASE}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  seed-db:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install deps
        run: npm i

      - name: seed
        run: npm run seed-prod
